services:
  mlflow:
    image: python:3.11-slim
    container_name: mlflow-server
    ports:
      - "8080:8080"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlartifacts:/mlflow/mlartifacts
    working_dir: /mlflow
    command: >
      bash -c "
        pip install mlflow &&
        mlflow server --host 0.0.0.0 --port 8080 --backend-store-uri file:///mlflow/mlruns --default-artifact-root file:///mlflow/mlartifacts
      "

  ml-api:
    build: .
    container_name: ml-api-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mlflow
    command: >
      bash -c "
        sleep 30 &&
        python src/train.py &&
        python src/api.py
      "
    environment:
      - PYTHONPATH=/app